

__author__ = "Siddharth Gabu"
__license__ = "MIT"
__version__ = "1.0"
__credits__ = "Josh Gordon - Google Developers"
__maintainer__ = "Siddharth Gabu"
__status__ = "Practice"

'''
Here is requirements

# Automatically generated by https://github.com/damnever/pigar.

numpy == 1.18.4
pydotplus == 2.0.2
scikit_learn == 0.24.0
six == 1.14.0

needs to download "graphviz tool" and set path in environment variables 

'''

import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()

print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])
for i in range(len(iris.target)):
    print("Example %d: label %s, features %s" % (i, iris.target[i], iris.data[i]))


test_idx = [0,50,100]

# training data
train_target = np.delete(iris.target,test_idx)
train_data = np.delete(iris.data,test_idx,axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf = clf.fit(train_data,train_target)

print(test_target)
#print(test_data)
print(clf.predict(test_data))

#viz code
from six import StringIO
import pydotplus
dot_data = StringIO()
tree.export_graphviz(clf,out_file=dot_data,
                        feature_names=iris.feature_names,
                        class_names=iris.target_names,
                        filled=True,rounded=True,
                        impurity=False)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")