__author__ = "Siddharth Gabu"
__license__ = "MIT"
__version__ = "1.0"
__credits__ = "Josh Gordon - Google Developers"
__maintainer__ = "Siddharth Gabu"
__status__ = "Practice"

'''
Here is requirements

# Automatically generated by https://github.com/damnever/pigar.

# Hello_world.py: 1
scikit_learn == 0.24.0

'''
from sklearn import tree

# features = [[140,"smooth"],[130,"smooth"],[150,"bumpy"],[170,"bumpy"]]
# smooth = 1
# bumpy = 0
features = [[140,1],[130,1],[150,0],[170,0]]
# labels = ["apple","apple","orange","orange"]
# apple = 0
# orange = 1
labels = [0,0,1,1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features,labels) # finding patterns in data
print(clf.predict([[150,0]]))